// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cumfit
List cumfit(NumericMatrix betanew2, double epsilon, int maxiter, NumericMatrix acoefs2, double lambda, NumericMatrix weight2, List control, NumericMatrix design2, int N, int n, int q, NumericMatrix resp2, NumericVector index, double c, double gama, std::string norm, int hatmatrix, double lambda2);
RcppExport SEXP BTLLasso_cumfit(SEXP betanew2SEXP, SEXP epsilonSEXP, SEXP maxiterSEXP, SEXP acoefs2SEXP, SEXP lambdaSEXP, SEXP weight2SEXP, SEXP controlSEXP, SEXP design2SEXP, SEXP NSEXP, SEXP nSEXP, SEXP qSEXP, SEXP resp2SEXP, SEXP indexSEXP, SEXP cSEXP, SEXP gamaSEXP, SEXP normSEXP, SEXP hatmatrixSEXP, SEXP lambda2SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type betanew2(betanew2SEXP );
        Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP );
        Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type acoefs2(acoefs2SEXP );
        Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type weight2(weight2SEXP );
        Rcpp::traits::input_parameter< List >::type control(controlSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type design2(design2SEXP );
        Rcpp::traits::input_parameter< int >::type N(NSEXP );
        Rcpp::traits::input_parameter< int >::type n(nSEXP );
        Rcpp::traits::input_parameter< int >::type q(qSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type resp2(resp2SEXP );
        Rcpp::traits::input_parameter< NumericVector >::type index(indexSEXP );
        Rcpp::traits::input_parameter< double >::type c(cSEXP );
        Rcpp::traits::input_parameter< double >::type gama(gamaSEXP );
        Rcpp::traits::input_parameter< std::string >::type norm(normSEXP );
        Rcpp::traits::input_parameter< int >::type hatmatrix(hatmatrixSEXP );
        Rcpp::traits::input_parameter< double >::type lambda2(lambda2SEXP );
        List __result = cumfit(betanew2, epsilon, maxiter, acoefs2, lambda, weight2, control, design2, N, n, q, resp2, index, c, gama, norm, hatmatrix, lambda2);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// binfit
List binfit(NumericMatrix betanew2, double epsilon, int maxiter, NumericMatrix acoefs2, double lambda, NumericMatrix weight2, List control, NumericMatrix design2, int N, int n, int q, NumericMatrix resp2, NumericVector index, double c, double gama, std::string norm, int hatmatrix, double lambda2);
RcppExport SEXP BTLLasso_binfit(SEXP betanew2SEXP, SEXP epsilonSEXP, SEXP maxiterSEXP, SEXP acoefs2SEXP, SEXP lambdaSEXP, SEXP weight2SEXP, SEXP controlSEXP, SEXP design2SEXP, SEXP NSEXP, SEXP nSEXP, SEXP qSEXP, SEXP resp2SEXP, SEXP indexSEXP, SEXP cSEXP, SEXP gamaSEXP, SEXP normSEXP, SEXP hatmatrixSEXP, SEXP lambda2SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type betanew2(betanew2SEXP );
        Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP );
        Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type acoefs2(acoefs2SEXP );
        Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type weight2(weight2SEXP );
        Rcpp::traits::input_parameter< List >::type control(controlSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type design2(design2SEXP );
        Rcpp::traits::input_parameter< int >::type N(NSEXP );
        Rcpp::traits::input_parameter< int >::type n(nSEXP );
        Rcpp::traits::input_parameter< int >::type q(qSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type resp2(resp2SEXP );
        Rcpp::traits::input_parameter< NumericVector >::type index(indexSEXP );
        Rcpp::traits::input_parameter< double >::type c(cSEXP );
        Rcpp::traits::input_parameter< double >::type gama(gamaSEXP );
        Rcpp::traits::input_parameter< std::string >::type norm(normSEXP );
        Rcpp::traits::input_parameter< int >::type hatmatrix(hatmatrixSEXP );
        Rcpp::traits::input_parameter< double >::type lambda2(lambda2SEXP );
        List __result = binfit(betanew2, epsilon, maxiter, acoefs2, lambda, weight2, control, design2, N, n, q, resp2, index, c, gama, norm, hatmatrix, lambda2);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
